version: 2

models:
  - name: fact_stock_prices
    description: "Fact table containing cleaned stock prices for all tickers"
    columns:
      - name: date
        description: "Trading date"
        tests:
          - not_null

      - name: company
        description: "Stock ticker"
        tests:
          - not_null

      - name: close
        description: "Closing price"
        tests:
          - not_null

      - name: volume
        description: "Trading volume"
        tests:
          - not_null
